### ISSUE TITLE
chroot raise segfault when deploying centos6u9

### ISSUE THREAD

**Issue by sheepcat** [tinkerbell/hook#101]
hi  guys：
i am deploying  centos6u9 
when  chroot in   /tinkerbell/cexec  action, it  raise  segfault error 15
i   think it's the VSYSCALL  problem
add  vsyscall=emulate  into  /proc/cmdline should work
but i don't know how to fix it  in linuxkit 

with great appreciate.

**Comment by chrisdoherty4** [comment]
Hi @sheepcat. Are you still experiencing this issue? There are some changes in boots that are going through review which will allow specifying custom cmdline args. Would that satisfy your use-case? 

https://github.com/tinkerbell/boots/pull/261

**Comment by jacobweinstock** [comment]
Hey @sheepcat , please try with the latest Hook, v0.9.1. If this is still an issue please feel free to reopen this ticket. Thanks!
