### ISSUE TITLE
question around use of `cpio`

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/hook#112]
I'm curious about the motivations around using `cpio` [here](https://github.com/tinkerbell/hook/blob/16a89f5fbdf1be008e4199407fcb24bd388cc1be/Makefile#L76) in the `Makefile`?
The artifacts that `linuxkit` builds with the cli flag `-format kernel+initrd` are sufficient to successfully netboot a machine.

I'm also asking because I haven't been able to produce locally built artifacts (`make dev-dist` and `make dist`) that successfully start their network interfaces on boot. I've only tested this on virtualbox and vmware fusion machines. When I just use the artifacts that `linuxkit` produces I don't see any issues.

CC @thebsdbox

**Comment by mmlb** [comment]
I came to the same conclusion, its unneeded. Give https://github.com/tinkerbell/hook/pull/105 a shot. It had working networking iirc.

**Comment by thebsdbox** [comment]
The original cpio bits where just to rebuild the initramfs. I would sometimes end up with a corrupt ramdisk directly from LinuxKit that could be repaired by extracting and repacking.

**Comment by jacobweinstock** [comment]
> The original cpio bits where just to rebuild the initramfs. I would sometimes end up with a corrupt ramdisk directly from LinuxKit that could be repaired by extracting and repacking. 

Ah interesting. Thanks for the context. If I might ask, how did you know when a ramdisk was corrupt?

**Comment by mmlb** [comment]
Going to close this issue. This is probably better off as a discussion.
