### ISSUE TITLE
Add multiple architectures

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/hook#14]
LinuxKit supports a platform flag that uses qemu to build on multi architectures.
We should use that to cover more architectures like `arm/6` and `7` for example

- [ ] add it to tar.gz

**Comment by deitch** [comment]
It actually isn't qemu. It uses the multi arch manifests (aka OCI index) to construct the bootable image. 😃

**Comment by nicklasfrahm** [comment]
@gianarb I could set this up. Would you mind if I use more standardized actions to make the CI pipeline more transparent?

**Comment by gianarb** [comment]
Any reason why you would like to do it? I want to keep Nix for a bit more to see if and how it can be useful. So I will prefer to leave it there for now.

https://github.com/gianarb/tinkie/pull/18 here I wrote a few tips if you want to contribute and don't know or don't want to use nix.

**Comment by nicklasfrahm** [comment]
Sure thing, thanks a lot for the PR!

**Comment by gianarb** [comment]
Fixed #28
