### ISSUE TITLE
Hook doesn't create required files/folder for docker trusted certificates

### ISSUE THREAD

**Issue by Paulius0112** [tinkerbell/hook#159]
We are trying to build according to https://anywhere.eks.amazonaws.com/docs/reference/baremetal/bare-custom-hookos/ as well as latest Hook version v.0.7.0. We updated `bootkit` and `hook-docker` folders with our custom functionality 
```
fmt.Println("Create docker cert directory - debug")
err = os.MkdirAll("/etc/docker/certs.d/<OUR IP>", os.ModeDir)
if err != nil {
        fmt.Println("Error creating dir")
        panic(err)
}
```

The code according to the logs inside IPXE machine suggest, that everything was executed correctly. However, no such directory exists on the host itself. 

Would it be possible to get more information regarding how to add a trusted docker certificate so that we could authenticate to our local docker registry.

**Comment by jacobweinstock** [comment]
Hey @Paulius0112. Are you wanting to add registry certificates to Hook at build time or runtime? Also, have you tried with the latest commit? We've made quite a few changes since the v0.7.0 release.

**Comment by Paulius0112** [comment]
We are trying to add on the build time, as it will be always the same cert. What does the latest commit implement so I could have a look?
