### ISSUE TITLE
How to enable docker insecure-registries on OSIE

### ISSUE THREAD

**Issue by bingzhangdai** [tinkerbell/hook#178]
I have an internal docker registry which uses HTTP protocol. Whenever we use internal tagged images in Actions, the installation process will get stuck. I then tried to pull the image from the console, it said "http: server gave HTTP resposne to HTTPS client".

## Expected Behaviour
can successfully pull the image

## Current Behaviour
Error response from daemon

## Possible Solution
passing args from server to hook.

## Steps to Reproduce (for bugs)
1. build or retag the action images and push them to local registries
2. local registries are using http protocol
3. use these images in action

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
Hey @bingzhangdai. Insecure docker registries are supported via the kernel parameter `insecure_registries=registry.example.com:5000,second.example.com:5000` (comma-separated). This can be set via the Boots [cli flag](https://github.com/tinkerbell/boots/blob/da970005705e1a670486933adc39b7a8b8c37d4c/cmd/boots/cli.go#L77) `--extra-kernel-args`.
