### ISSUE TITLE
Possible Bug In VLAN parsing

### ISSUE THREAD

**Issue by dvintel** [tinkerbell/hook#180]
On line: https://github.com/tinkerbell/hook/blob/1c438a9b6dbd72a5611c54a0b60bd0dfc8a87888/files/dhcp.sh#L14C19-L14C50

The command: 

```shell
sed -n 's/.*vlan_id=\([0-9]*\).*/\1/p' /proc/cmdline
```

will also match the string: `testvlan_id=2`.

I am expecting that it would only match on `vlan_id=2`
**Note:** only match on `vlan_id=` rather than also on `testvlan_id=`

**Comment by dvintel** [comment]
One possible solution would be to change the sed command to something like:

``` shell
's/.* vlan_id=\([0-9]*\).*/\1/p'
```

add a space before the `vlan_id=`

**Comment by jacobweinstock** [comment]
Hey @dvintel, thanks for finding and reporting this! I've opened #181 to resolve this. Thanks!
