### ISSUE TITLE
Ability to signal host shutdown

### ISSUE THREAD

**Issue by jasonyates-thg** [tinkerbell/hook#189]
It would be useful to be able to signal the host system to shutdown in the same fashion we are able to signal the system to reboot via writing `/worker/reboot`

My use case is a deprovisioning workflow that erases disks, profiles the hardware and then ideally shuts the system down

**Comment by jacobweinstock** [comment]
This is being tracked with https://github.com/tinkerbell/roadmap/issues/29. This will most likely be added as a built-in to tink worker in the future. For the moment, an Action like https://github.com/jacobweinstock/waitdaemon can shutdown a host.
