### ISSUE TITLE
ARM64 server gets stuck on "bpfilter write fail: -32" when activating Linuxkit (Alpine)

### ISSUE THREAD

**Issue by howard-yeh** [tinkerbell/hook#196]
When I provisioned the ARM64 server, the admin console stucked with the following error messages
[ 21.345242] arm_spe_pmu arm,spe-v1: profiling buffer inaccessible. Try passing "kpti=off" on the kernel command line
[ 21.364371] arm_spe_pmu: probe of arm,spe-v1 failed with error -1
and it stucks looping in "bpfilter: write fail -32".

Here's the related issue that I found: AmpereComputing/ampere-lts-kernel#21

Is there any possible solution for this case?

BTW, the x86 server can be provisioned correctly.

## Expected Behaviour

Activate hook-bookit and hook-docker containers and enter os console.
## Current Behaviour

the admin console stucked with the following error messages
[ 21.345242] arm_spe_pmu arm,spe-v1: profiling buffer inaccessible. Try passing "kpti=off" on the kernel command line
[ 21.364371] arm_spe_pmu: probe of arm,spe-v1 failed with error -1
## Steps to Reproduce (for bugs)

1. Setup Tinkerbell stack with helm chart
2. Apply hardware.yml , template. yml and workflow.yml

## Your Environment

Tinkerbell version: v0.4.2
Hook version: v0.8.1
Arch: ARM64v8

**Comment by jacobweinstock** [comment]
Hey @howard-yeh . We've updated the build process a lot. This issue should be resolved now. Please try using v0.9.0 and feel free to reopen this if the issue persists.
