### ISSUE TITLE
How to make a customer build of HookOS

### ISSUE THREAD

**Issue by ygao-armada** [tinkerbell/hook#242]
I try to follow instruction on [Customize HookOS for EKS Anywhere on Bare Metal](https://anywhere.eks.amazonaws.com/docs/getting-started/baremetal/customize/bare-custom-hookos/) , however, what is file "build.sh" in following commands?

- ./build.sh kernel-config hook-latest-lts-amd64
- ./build.sh kernel hook-latest-lts-amd64
- ./build.sh linuxkit hook-latest-lts-amd64 

And when I try to run command "make dist", I see follow errors:
```
ubuntu@demo-vs-admin-vm-ls03:~/repos/hook$ make dist
linuxkit build -docker -arch amd64 -format tar-kernel-initrd -name hook -dir out/sha-6af827a/rel/amd64 out/sha-6af827a/rel/amd64/hook.yaml
bash: line 1: linuxkit: command not found
make: *** [rules.mk:49: out/sha-6af827a/rel/amd64/hook.tar] Error 127
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.3 LTS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
Hey @ygao-armada , `make dist` is an old way of building HookOS. Please check that you have the latest commit of the repo. I think this might be the same issue that we discussed and resolve via slack. If not, please do reopen the issue. Thanks!
