### ISSUE TITLE
Push-based publish job is failing

### ISSUE THREAD

**Issue by detiber** [tinkerbell/hook#32]
## Expected Behaviour

Current publish job is referencing a non-existing s3 bucket and does not have credentials, example failure: https://github.com/tinkerbell/hook/actions/runs/559080308

**Comment by gianarb** [comment]
@rawkode is on it asking CNCF for an AWS|GCP access to get an s3 bucket up and running for us.

**Comment by rawkode** [comment]
the `cncf/cluster` repo is for requesting EM resources only, so I'm currently finding out the best course of action. I'll update later today.

**Comment by detiber** [comment]
https://github.com/tinkerbell/infrastructure/issues/8

**Comment by thebsdbox** [comment]
I guess not, we can easily had a few lines together that parse the GitHub API and get a release URL to download.
