### ISSUE TITLE
Need to add an automated workflow to build kconfig image referenced in the kernel README.md file

### ISSUE THREAD

**Issue by detiber** [tinkerbell/hook#34]
## Expected Behaviour

The kernel readme references a non-existing kconfig image: https://github.com/tinkerbell/hook/blob/master/kernel/README.md

We should automate the building/publishing of this image based on changes to the kernel version we are targeting.

This will require:
-  a new quay.io repository to be created (quay.io/tinkerbell/hook-kconfig)
- The readme to reference the new image
- A new push job added to the github workflows to build/push the hook-kconfig image when needed

**Comment by jacobweinstock** [comment]
The new build process handles this now.
