### ISSUE TITLE
why is dhcpcd being added to onboot?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/hook#56]
why is `dhcpcd` being added to `onboot`?

https://github.com/tinkerbell/hook/blob/7b6437815df9b89fd55fb76d1584a65098df04ab/hook.yaml#L14-L16

the [commit that introduced those changes](https://github.com/tinkerbell/hook/commit/6e103995333cb58a1a6af0b66cee1e5e77d4e0d5) does not describe why.

the differences between hook.yaml and hook_debug.yaml should only be in the later having the `sshd` service? if so, can the two files reflect that?

**Comment by thebsdbox** [comment]
So! The reason that we do a `dhcpd` on `onboot`, is because onboot executes before services and services are all started in parallel. The problem with dhcpd happening in services is that dhcpd can take too long before dockerd tries to pull an image with no network config.
