### ISSUE TITLE
Automate GitHub release workflow

### ISSUE THREAD

**Issue by tstromberg** [tinkerbell/hook#78]
This will help standardize our way out of issues like https://github.com/tinkerbell/hook/issues/75

This process should handle re-releases where there is a -<iteration> suffix on the filename.

**Comment by nicklasfrahm** [comment]
I have not yet worked with in detail with this, but [semantic-release](https://github.com/semantic-release/semantic-release) could be a good option here. I will submit a PR if this makes sense for you.

**Comment by mmlb** [comment]
@tstromberg do you have any more details you can provide here? Is [semantic-release](https://github.com/semantic-release/semantic-release) as mentioned by @nicklasfrahm along the lines of what you were thinking?

**Comment by jacobweinstock** [comment]
Going to close this as we are using semantic versioning and have GitHub actions that have automated the release process and a RELEASING.md with a helper script that is in line with the other repositories in the Tinkerbell org.
