### ISSUE TITLE
Add alias docker="ctr -n services.linuxkit t exec -t --exec-id test docker docker" to the default releases of Hook

### ISSUE THREAD

**Issue by djpbessems** [tinkerbell/hook#81]
Add alias docker="ctr -n services.linuxkit t exec -t --exec-id test docker docker" to the default releases of Hook

## Expected Behaviour
For convenience, the docker-cli should be available on a tink-worker (`docker ps -a` / `docker logs tink-server` / etc).

## Current Behaviour
One has to first create an alias `docker` before being able to interact with the container runtime on a tink-worker

## Possible Solution
Possibly a way to include an alias is described here: https://github.com/linuxkit/linuxkit/issues/2364

## Steps to Reproduce (for bugs)
n/a

## Context
We've had serious issues troubleshooting why tink-workers were not starting their assigned workflows, and everytime a machine booted into LinuxKit we had to add this alias to see the actual status of the machine. To put it mildly, it was cumbersome :D

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by tstromberg** [comment]
I for one thinks this sounds like a solid idea :)

**Comment by rgl** [comment]
This can be done with https://github.com/rgl/linuxkit-vagrant/blob/04d2a974bc7f89c56b1aaa309fd06769e11e3444/linuxkit-example.yml#L95-L101:

```yaml
files:
  - path: etc/profile.d/local.sh
    contents: |
      alias logread='/proc/1/root/usr/bin/logread'
      alias l='ls -lF'
      alias ll='l -a'
      alias ctr='ctr -n services.linuxkit'
      alias docker='ctr tasks exec --tty --exec-id shell docker docker'
```
