### ISSUE TITLE
Add support for virtio scsi

### ISSUE THREAD

**Issue by rgl** [tinkerbell/hook#84]
I want to use the virtio scsi transport but the current hook linux kernel is missing the `CONFIG_SCSI_VIRTIO=y` setting.

## Expected Behaviour

When I use the following vagrant snippet I was expecting to see a `/dev/sda` device.

```ruby
      config.vm.provider :libvirt do |lv, config|
        lv.storage :file, :size => '40G', :bus => 'scsi', :discard => 'unmap', :cache => 'unsafe'
```

## Current Behaviour

There is no `/dev/sda` device.

## Possible Solution

Compile linux with `CONFIG_SCSI_VIRTIO=y`.

## Steps to Reproduce (for bugs)

1. modify the sandbox vagrantfile to use `lv.storage :file, :size => '40G', :bus => 'scsi', :discard => 'unmap', :cache => 'unsafe'`

**Comment by tstromberg** [comment]
If you are able to propose a PR that fixes this, I'm fairly sure it would be safe to merge - and certainly useful for testing.

@thebsdbox - any thoughts here?

**Comment by rgl** [comment]
I was trying to start doing this, but the instructions at https://github.com/tinkerbell/hook/tree/main/kernel#modify-the-kernel use the non-available quay.io/tinkerbell/kconfig image:

```console
rgl@rgl-desktop:~/Projects/tinkerbell-hook/kernel$ docker run --rm -ti -v $(pwd):/src:z --platform=linux/amd64 quay.io/tinkerbell/kconfig
Unable to find image 'quay.io/tinkerbell/kconfig:latest' locally
docker: Error response from daemon: unauthorized: access to the requested resource is not authorized.
See 'docker run --help'.
```

And looking at quay, it also fails with that error: https://quay.io/tinkerbell/kconfig

Can that image made available? Or an alternative proposed?

**Comment by rgl** [comment]
Hook linux is working fine! sorry for the noise...

The problem is in my local setup. When the vagrant-libvirt provider creates a libvirt domain it does not define a scsi controller, so libvirt will automatically add a `lsilogic` scsi controller, which linux has no driver for it, so no `sda` device is ever created.

I was able to [make it work with a workaround](https://github.com/vagrant-libvirt/vagrant-libvirt/pull/692#issuecomment-922329049) that modifies the VM configuration to use the `virtio-scsi` scsi controller.
