### ISSUE TITLE
CI failures due to missing s3 credentials

### ISSUE THREAD

**Issue by ScottGarman** [tinkerbell/hook#93]
CI is currently failing during the publish step with the following error:

```
s3cmd sync ./hook-2e5df3fffd5c16a24153262d4179f059123994c9.tar.gz s3://s.gianarb.it/hook/2e5df3fffd5c16a24153262d4179f059123994c9.tar.gz
ERROR: /home/runner/.s3cfg: None
ERROR: Configuration file not available.
```

The missing s3 credentials need to be added. I'm not too familiar with the history of this codebase, but at first glance I also find it odd that we're uploading artifacts to `s.gianarb.it` - so perhaps that is the main issue here?

**Comment by mmlb** [comment]
Is this on main branch or in PRs?

**Comment by cprivite** [comment]
hook/Makefile references that s3 repo, apparently needs some massaging.

**Comment by jacobweinstock** [comment]
closing as `s3cmd` is no longer in use.
